version: "3.3"
services:
  # db:
  #   image: postgres:14-alpine
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   env_file: .env

  web:
    build: ./video_server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./video_server:/usr/src/app
    ports:
      - 8080:8080
    #env_file: .env
    # depends_on:
    #   - db
