# Generated by Django 4.1.4 on 2022-12-08 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='file_id',
            new_name='fileid',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='updated',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time when the data was saved on the server side.', null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='name',
            field=models.CharField(blank=True, help_text='filename', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='size',
            field=models.FloatField(help_text='file size (bytes)', null=True),
        ),
    ]
