# Generated by Django 4.1.4 on 2022-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_file_id_videomodel_fileid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='name',
            field=models.CharField(default='', help_text='filename', max_length=260),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='size',
            field=models.IntegerField(help_text='file size (bytes)', null=True),
        ),
    ]
