# Generated by Django 4.1.4 on 2022-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_videomodel_name_alter_videomodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
