# Generated by Django 4.1.4 on 2022-12-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_videomodel_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='size',
        ),
    ]
