# Generated by Django 4.1.4 on 2022-12-08 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_videomodel_created_at_remove_videomodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='video_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time when the data was saved on the server side.', null=True),
        ),
    ]
