# Generated by Django 4.1.4 on 2022-12-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_video_file_videomodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='name',
            field=models.CharField(default='', help_text='filename', max_length=260),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='size',
            field=models.IntegerField(help_text='file size (bytes)', null=True),
        ),
    ]
