# Generated by Django 4.1.4 on 2022-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_videomodel_name_videomodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='name',
            field=models.CharField(default='', help_text='filename', max_length=260, null=True),
        ),
    ]
