# Generated by Django 4.1.4 on 2022-12-09 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_videomodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpeg'])], verbose_name=''),
        ),
    ]
