# Generated by Django 4.1.4 on 2022-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_videomodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
