# Generated by Django 4.1.4 on 2022-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_videomodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='fileid',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
