# Generated by Django 4.1.4 on 2022-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_videomodel_fileid_videomodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='id',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='fileid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
