# Generated by Django 4.1.4 on 2022-12-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_remove_videomodel_id_videomodel_fileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='mime_type',
            field=models.CharField(help_text="Content's MIME Type", max_length=255, null=True),
        ),
    ]
