# Generated by Django 4.1.4 on 2022-12-15 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_videomodel_mime_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='fileid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time when data was saved on server', null=True),
        ),
    ]
