# Generated by Django 4.1.4 on 2022-12-15 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_rename_fileid_videomodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='fileid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
