# Generated by Django 4.1.4 on 2022-12-15 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_videomodel_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='fileid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
